"""
MediAssist AI — Streamlit UI (Week 4)
=====================================
A client-facing interface over the Week-3 RAG pipeline.

Layout:
  - Sidebar: search PubMed for articles, preview them, then ingest the selected
    ones into the Chroma vector store.
  - Main:    a query bar to ask questions; answers are generated by the RAG
    pipeline (retrieve from Chroma -> Groq Llama 3) with cited sources.

Run:
    streamlit run app.py
"""

import os
import sys

import streamlit as st

# --------------------------------------------------------------------------- #
# Reuse the Week-3 modules (pubmed / chroma_store / ingest / rag) without
# duplicating them: add the Week-3 folder to the import path.
# --------------------------------------------------------------------------- #
HERE = os.path.dirname(os.path.abspath(__file__))
WEEK3 = os.path.abspath(os.path.join(HERE, "..", "Week 3"))
if WEEK3 not in sys.path:
    sys.path.insert(0, WEEK3)

from pubmed import PubMedRetriever          # noqa: E402
from chroma_store import ChromaStore        # noqa: E402
from ingest import article_to_document      # noqa: E402
import rag                                  # noqa: E402

# The vector store + the .env (Groq key) both live in the Week-3 folder, so we
# point Chroma at the Week-3 persist dir explicitly (CWD-independent).
CHROMA_DIR = os.path.join(WEEK3, "chroma_db")
MAX_ARTICLES_CAP = 300

st.set_page_config(page_title="MediAssist AI", page_icon="🩺", layout="wide")


# --------------------------------------------------------------------------- #
# Cached resources
# --------------------------------------------------------------------------- #
@st.cache_resource(show_spinner="Connecting to the vector store…")
def get_store():
    return ChromaStore(persist_dir=CHROMA_DIR)


store = get_store()

# session state for search results between reruns
st.session_state.setdefault("search_results", [])   # list of fetched article dicts
st.session_state.setdefault("search_term", "")


# --------------------------------------------------------------------------- #
# Sidebar — search + ingest
# --------------------------------------------------------------------------- #
with st.sidebar:
    st.header("🔎 Find & ingest articles")
    st.caption("Search PubMed, preview the results, then add them to the "
               "knowledge base.")

    term = st.text_input("Search term", value="intermittent fasting",
                         placeholder="e.g. time-restricted eating diabetes")
    n_articles = st.slider("Max articles", min_value=5, max_value=MAX_ARTICLES_CAP,
                           value=20, step=5,
                           help="Capped at 300 to respect the PubMed rate limit.")

    if st.button("Search PubMed", type="primary", use_container_width=True):
        if not term.strip():
            st.warning("Enter a search term first.")
        else:
            with st.spinner(f"Searching PubMed for '{term}'…"):
                pmids = PubMedRetriever.search_pubmed_articles(
                    term.strip(), max_results=min(n_articles, MAX_ARTICLES_CAP))
                articles = PubMedRetriever.fetch_pubmed_abstracts(pmids) if pmids else []
            st.session_state["search_results"] = articles
            st.session_state["search_term"] = term.strip()
            if not articles:
                st.error("No articles found for that term.")

    results = st.session_state["search_results"]

    if results:
        st.success(f"Found {len(results)} articles for "
                   f"'{st.session_state['search_term']}'.")
        with st.expander("Preview results", expanded=True):
            for art in results[:50]:
                st.markdown(
                    f"**[{art['pmid']}]** {art.get('title', 'No Title')}  \n"
                    f"<small>{art.get('journal', '')} · "
                    f"{art.get('publication_date', '')}</small>",
                    unsafe_allow_html=True,
                )
            if len(results) > 50:
                st.caption(f"… and {len(results) - 50} more.")

        if st.button(f"⬇️ Ingest {len(results)} articles into vector store",
                     type="primary", use_container_width=True):
            with st.spinner("Embedding and storing documents…"):
                ids, docs, metas = [], [], []
                for art in results:
                    pmid, doc, meta = article_to_document(art)
                    ids.append(pmid); docs.append(doc); metas.append(meta)
                added = store.add_documents(ids=ids, documents=docs, metadatas=metas)
            st.success(f"Ingested {added} articles. "
                       f"Knowledge base now holds {store.count()} documents.")
            get_store.clear()   # refresh cached count on next run

    st.divider()
    st.metric("Documents in vector store", store.count())


# --------------------------------------------------------------------------- #
# Main — query bar + answer
# --------------------------------------------------------------------------- #
st.title("🩺 MediAssist AI")
st.caption("Evidence-based answers on intermittent fasting, grounded in the "
           "PubMed articles you've ingested.")

if store.count() == 0:
    st.info("👈 The knowledge base is empty. Use the sidebar to search PubMed "
            "and ingest some articles first.")
    st.stop()

col_q, col_n = st.columns([5, 1])
with col_q:
    question = st.text_input(
        "Ask a question",
        placeholder="e.g. Is 16:8 fasting effective for type 2 diabetes?",
        label_visibility="collapsed",
    )
with col_n:
    top_k = st.number_input("Sources", min_value=1, max_value=10, value=5,
                            label_visibility="collapsed")

ask = st.button("Ask", type="primary")

if ask:
    if not question.strip():
        st.warning("Type a question first.")
    else:
        try:
            with st.spinner("Retrieving evidence and generating an answer…"):
                result = rag.answer_query(question.strip(),
                                          n_results=int(top_k), store=store)
        except Exception as e:
            st.error(f"Could not generate an answer: {e}")
            st.stop()

        st.subheader("Answer")
        st.write(result["answer"])

        # Sources are shown only when the answer is actually grounded in the
        # ingested documents (relevant retrieval + no refusal). For off-topic
        # or unanswerable questions, no sources are listed.
        if result["sources"]:
            st.subheader("Sources")
            for s in result["sources"]:
                dist = s.get("distance")
                dist_str = f"{dist:.3f}" if dist is not None else "n/a"
                st.markdown(
                    f"- **[{s['pmid']}]** {s.get('title', '')}  "
                    f"(distance {dist_str})  \n  {s.get('url', '')}"
                )
        else:
            st.caption("ℹ️ This answer is not based on the stored documents, "
                       "so no sources are shown.")
